input_sentence: "Today was cooler than usual, the sun was out and I loved the occassional cool breezes"

review_list: ["perfect lighting system when the lights go out. Battery life is excellent when fully charged can last up to 4 -5 days until it needs to be recharged again. Simple just leave it in the sun.",
               "Works very good last long even bought a second one 👌",
               "lasted 5 months, with little use and battery dead. Absolute garbage, definitely not worth the money. RUBBISH",
               "This product was only useful for the first 30 days, after that the battery doesn’t even last for 20 minutes. Will definitely not recommend buying this,",
               "Good for lighting... Doesn't charge or support most of the phones..."]
